(in-package :cl-info)
(let (
(deffn-defvr-pairs '(
; CONTENT: (<INDEX TOPIC> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS> <NODE NAME>))
("boolean_form" . ("logic.info" 11767 541 "Definitions for logic"))
("characteristic_vector" . ("logic.info" 3213 1297 "Definitions for logic"))
("closed_under_f" . ("logic.info" 6590 397 "Definitions for logic"))
("closed_under_t" . ("logic.info" 6988 394 "Definitions for logic"))
("demorgan" . ("logic.info" 12309 380 "Definitions for logic"))
("dual_function" . ("logic.info" 5793 353 "Definitions for logic"))
("functionally_complete" . ("logic.info" 9120 626 "Definitions for logic"))
("linear" . ("logic.info" 8516 603 "Definitions for logic"))
("logic_basis" . ("logic.info" 9747 1437 "Definitions for logic"))
("logic_diff" . ("logic.info" 11185 581 "Definitions for logic"))
("logic_equiv" . ("logic.info" 5061 731 "Definitions for logic"))
("logic_simp" . ("logic.info" 2551 661 "Definitions for logic"))
("monotonic" . ("logic.info" 7383 1132 "Definitions for logic"))
("pcnf" . ("logic.info" 12938 226 "Definitions for logic"))
("pdnf" . ("logic.info" 12690 247 "Definitions for logic"))
("self_dual" . ("logic.info" 6147 442 "Definitions for logic"))
("zhegalkin_form" . ("logic.info" 4511 549 "Definitions for logic"))
))
(section-pairs '(
; CONTENT: (<NODE NAME> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS>))
("Definitions for logic" . ("logic.info" 2499 10665))
("Introduction to logic" . ("logic.info" 561 1812))
)))
(load-info-hashtables (maxima::maxima-load-pathname-directory) deffn-defvr-pairs section-pairs))
