VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IXMLDOMNode"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
' Dummy for IXMLDOMNode
'
Public Function nodeType() As Integer
'
End Function
Public Property Get nodeValue() As String
'
End Property
Public Property Let nodeValue(RHS As String)
'
End Property
Public Function myChildren() As Collection
'
End Function
Public Function myAttNames() As Collection
'
End Function
Public Function myAttValues() As Collection
'
End Function
'
Public Sub Save(dest As Variant)
'
End Sub
